# -*- coding: utf-8 -*-
"""img resize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bwwiN_hMc4y_8SMhl1tW_Ct5gj_wAllm
"""

import os
from PIL import Image

def resize_images(input_folder, output_folder, size):

    if not os.path.exists(output_folder):
        os.makedirs(output_folder)
    for filename in os.listdir(input_folder):
        if filename.endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp')):

            img_path = os.path.join(input_folder, filename)

            with Image.open(img_path) as img:

                img_resized = img.resize(size)

                img_resized.save(os.path.join(output_folder, filename))
                print(f'Resized and saved: {filename}')

if __name__ == "__main__":

    input_folder = r"C:\Users\DELL\OneDrive\Desktop\img"
    output_folder = r"C:\Users\DELL\OneDrive\Desktop\img"
    size = (800, 600)

    resize_images(input_folder, output_folder, size)

